"""user table update

Revision ID: 5f1758701f8c
Revises: 
Create Date: 2020-11-27 23:55:49.788145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f1758701f8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_parkinson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_parkinson_email'), 'user_parkinson', ['email'], unique=True)
    op.create_index(op.f('ix_user_parkinson_name'), 'user_parkinson', ['name'], unique=False)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_name', table_name='user')
    op.drop_table('user')
    op.drop_constraint('parkinson_control_user_id_fkey', 'parkinson_control', type_='foreignkey')
    op.create_foreign_key(None, 'parkinson_control', 'user_parkinson', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parkinson_control', type_='foreignkey')
    op.create_foreign_key('parkinson_control_user_id_fkey', 'parkinson_control', 'user', ['user_id'], ['id'])
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_user_parkinson_name'), table_name='user_parkinson')
    op.drop_index(op.f('ix_user_parkinson_email'), table_name='user_parkinson')
    op.drop_table('user_parkinson')
    # ### end Alembic commands ###
