"""datetime added to feeling

Revision ID: a6178b301f4f
Revises: 33a0e1440eef
Create Date: 2020-12-06 21:27:30.395000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6178b301f4f'
down_revision = '33a0e1440eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeling', sa.Column('strattime', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_feeling_strattime'), 'feeling', ['strattime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feeling_strattime'), table_name='feeling')
    op.drop_column('feeling', 'strattime')
    # ### end Alembic commands ###
